Spring:
  application:
    name: trade-service
  redis:
    host: localhost
    port: 6379
  data:
    redis:
      repositories:
        enabled: true
  threads:
    virtual:
      enabled: true
      timeout: 1000
      stack-size: 1M
      debug: false